### ISSUE TITLE
System hangs while building 

### ISSUE THREAD

**Issue by RemyDuron** [sdsc/cern-roll#3]
I am trying to install the CERN roll on a Rocks Cluster version 6.2. 

I have previously installed the SDSC roll, the cmake roll, and the gnucompiler roll. 

After entering the "make 2>&1" command, the system will eventually hang or freeze entirely. This does not happen at the same point in the process every time I try it, but does always seem to happen while "Building CXX object. . . ". I have left the cluster in that state for 24 hours and it has remained frozen, so I do not think it will eventually complete. 

When I run the make command with the "-d" flag to include debug information, it does not hang but instead stops with an error 2. 

I have included the logs from two attempts at building without the debug information (showing it stopping at different points in the process) and one build log with the debug information. 

I would be grateful for any assistance you could give me with this problem. I looked in the previous issues and saw a similar problem posted there that was the result of the / partition becoming full, but this is not the case for me (I have over 40 gigabytes free).

[cernrollbuilddebuglog.txt](https://github.com/sdsc/cern-roll/files/445767/cernrollbuilddebuglog.txt)
[cernrollbuild2log.txt](https://github.com/sdsc/cern-roll/files/445768/cernrollbuild2log.txt)
[cernrollbuild1log.txt](https://github.com/sdsc/cern-roll/files/445769/cernrollbuild1log.txt)

**Comment by tcooper** [comment]
@schulsey Sorry to find you were left hanging on this. I can only assume you worked out your issue and/or got an answer from elsewhere. In case you didn't and for future reference you build stopped because your build machine needed the sqlite-devel RPM installed. That is missing in the roll README file as a dependency. We'll get that added. Closing this issue for it's embarrassingly long open duration.
